/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#68645b',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2f312f',
        'on-error-container': '#93000a',
        'inverse-primary': '#aacfb4',
        'surface-container': '#efeeeb',
        'surface-container-highest': '#e3e2e0',
        'secondary-container': '#e8e2d6',
        outline: '#727972',
        secondary: '#625e55',
        'primary-fixed-dim': '#aacfb4',
        'tertiary-container': '#94b19f',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-high': '#e9e8e5',
        'on-tertiary-fixed': '#062014',
        'surface-dim': '#dbdad7',
        'on-tertiary-fixed-variant': '#324c3e',
        'primary-container': '#8fb399',
        'on-background': '#1a1c1a',
        'outline-variant': '#c2c8c1',
        'on-secondary-fixed-variant': '#4a473e',
        tertiary: '#496455',
        'surface-container-low': '#f4f3f1',
        'on-primary-fixed-variant': '#2d4e39',
        'on-primary-container': '#254631',
        'primary-fixed': '#c6eccf',
        'tertiary-fixed-dim': '#b0cdbb',
        'secondary-fixed-dim': '#cbc6ba',
        'on-surface-variant': '#424843',
        'on-primary-fixed': '#002110',
        'on-error': '#ffffff',
        'on-tertiary-container': '#2a4436',
        'on-secondary-fixed': '#1e1c14',
        'surface-tint': '#44664f',
        'inverse-on-surface': '#f2f1ee',
        'surface-variant': '#e3e2e0',
        'secondary-fixed': '#e8e2d6',
        surface: '#faf9f6',
        'surface-bright': '#faf9f6',
        primary: '#44664f',
        'on-surface': '#1a1c1a',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ccead6',
        'on-tertiary': '#ffffff',
        background: '#faf9f6',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-tablet': '32px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        gutter: '24px',
        unit: '8px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        body: ['Manrope', 'sans-serif'],
        display: ['Libre Caslon Text', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      boxShadow: {
        soft: '0 4px 20px rgba(45, 71, 57, 0.04)',
        'soft-lg': '0 8px 30px rgba(45, 71, 57, 0.08)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
